[package]
name = "my_script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "*"
ast = {path="./ast"}
frontend ={path = "./frontend"}
backend ={path = "./backend"}